version: '3'
services:
  redis:  
    image: redis:6.2.6-alpine
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASS}\""]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
#      - ./sysctl.conf:/etc/sysctl.conf
      - /tmp/chat-sample/data:/data
    ports:
      - "6379:6379"
